#! /bin/sh
#
# S99agsd	This script runs the user program /etc/ags/agsd.
#		It is started at boot time and can be restarted and stopped.
#
# Version:	1.0
#
start() {
  printf "Starting AGS LASERVISION daemon"
  start-stop-daemon -S -q -p /var/run/agsd.pid --exec /etc/ags/agsd
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
  printf "Stopping AGS daemon: "
  start-stop-daemon -K -q -p /var/run/agsd.pid
  [ $? = 0 ] && echo "OK" || echo "FAIL"
  ifdown eth0
}

restart() {
  stop
  sleep 1
  ifup eth0
  sleep 1
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
