#! /bin/sh
#
# S99agsd	This script runs the user program /laservision/sbin/agsd.
#		It is started at boot time and can be restarted and stopped.
#
# Version:	1.0
#
start() {
    printf "Starting AGS LASERVISION daemon"
    mount -a
    start-stop-daemon -b -S -q -m -p /var/run/agsd.pid --exec /laservision/sbin/agsd -- -n
    echo "OK"
}

stop() {
  printf "Stopping AGS LASERVISION daemon: "
  start-stop-daemon -K -q -p /var/run/agsd.pid
  echo "OK"
  ifdown eth0
}

restart() {
  printf "Restarting AGS LASERVISION daemon"
  stop
  sleep 1
  ifup eth0
  sleep 1
  start
  echo "OK"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
